generators:
- |-
  apiVersion: fn.kpt.dev/v1alpha1
  kind: RenderHelmChart
  metadata:
    name: demo
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: render-helm-chart
  helmGlobals:
    configHome: ./tmp
  helmCharts:
  - chartArgs:
      name: argo-rollouts
      version: 2.21.1
      repo: https://argoproj.github.io/argo-helm
    templateOptions:
      releaseName: myargo
