generators:
- |-
  apiVersion: fn.kpt.dev/v1alpha1
  kind: RenderHelmChart
  metadata:
    name: demo
    annotations:
      config.kubernetes.io/function: |
        container:
          network: true
          image: gcr.io/kpt-fn/render-helm-chart:v0.2.1
  helmCharts:
  - chartArgs:
      name: argo-rollouts
      version: 2.21.1
      repo: https://argoproj.github.io/argo-helm
    templateOptions:
      namespace: mynamespace
      releaseName: moria
